# Clé unique du projet dans SonarQube
sonar.projectKey=WonderBookBackTEST
sonar.projectName=WonderBookBackTEST
sonar.projectVersion=1.0

# Chemin relatif au fichier sonar-project.properties
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclure les fichiers de test et node_modules
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js
sonar.tests=.
sonar.test.inclusions=**/*.test.js,**/*.spec.js
